default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_blog_api_development

test:
  <<: *default
  database: mini_blog_api_test

production:
  <<: *default
  database: mini_blog_api_production
  username: mini_blog_api
  password: <%= ENV["MINI_BLOG_API_DATABASE_PASSWORD"] %>